
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TenteBrigandEstAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1537, 1, 4, 20}, {878, -1, -4, 0}, {878, 0, -4, 0}// 31	49	50	
			, {878, 1, -4, 0}, {878, 2, -4, 0}, {879, -3, 2, 0}// 51	53	64	
			, {879, -3, -2, 0}, {879, -3, 1, 0}, {879, -3, 0, 0}// 65	66	67	
			, {879, -3, -1, 0}, {879, -3, 3, 0}, {879, -3, -3, 0}// 68	69	72	
			, {878, -2, -4, 0}, {875, -3, -4, 0}// 73	74	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TenteBrigandEstAddonDeed();
			}
		}

		[ Constructable ]
		public TenteBrigandEstAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1535, 0, 1, 26, 1911, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1535, 0, 0, 26, 1911, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1538, 1, 1, 26, 1911, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1538, 1, 0, 26, 1911, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1541, 1, -1, 26, 1911, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1542, 0, -1, 26, 1911, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1543, 0, 2, 26, 1911, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1540, 1, 2, 26, 1911, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1536, 1, -2, 23, 1911, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1536, 0, -2, 23, 1911, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1535, -1, 2, 23, 1911, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1535, -1, 1, 23, 1911, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1535, -1, 0, 23, 1911, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1535, -1, -1, 23, 1911, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1537, 1, 3, 23, 1911, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1537, 0, 3, 23, 1911, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1538, 2, 2, 23, 1911, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1538, 2, 1, 23, 1911, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1538, 2, 0, 23, 1911, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1538, 2, -1, 23, 1911, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1542, -1, -2, 23, 1911, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1541, 2, -2, 23, 1911, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1540, 2, 3, 23, 1911, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1543, -1, 3, 23, 1911, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1536, 2, -3, 20, 1911, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1536, 1, -3, 20, 1911, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1536, 0, -3, 20, 1911, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1536, -1, -3, 20, 1911, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1537, 2, 4, 20, 1911, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1537, 1, 4, 20, 1911, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1537, 0, 4, 20, 1911, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1537, -1, 4, 20, 1911, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1538, 3, 3, 20, 1911, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1538, 3, 2, 20, 1911, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1538, 3, 1, 20, 1911, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1538, 3, 0, 20, 1911, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1538, 3, -1, 20, 1911, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1538, 3, -2, 20, 1911, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1541, 3, -3, 20, 1911, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1540, 3, 4, 20, 1911, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 872, 3, 4, 0, 1911, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 873, -1, 4, 0, 1911, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 873, 0, 4, 0, 1911, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 874, 3, -3, 0, 1911, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 874, 3, 2, 0, 1911, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 874, 3, -2, 0, 1911, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 874, 3, 3, 0, 1911, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 877, 3, -4, 0, 1911, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 873, 1, 4, 0, 1911, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 873, 2, 4, 0, 1911, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1535, -2, 3, 20, 1911, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1535, -2, 2, 20, 1911, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1535, -2, 1, 20, 1911, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1535, -2, 0, 20, 1911, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1535, -2, -1, 20, 1911, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1535, -2, -2, 20, 1911, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1542, -2, -3, 20, 1911, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1543, -2, 4, 20, 1911, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 873, -2, 4, 0, 1911, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 876, -3, 4, 1, 1911, -1, "", 1);// 71

		}

		public TenteBrigandEstAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TenteBrigandEstAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TenteBrigandEstAddon();
			}
		}

		[Constructable]
		public TenteBrigandEstAddonDeed()
		{
			Name = "TenteBrigandEst";
		}

		public TenteBrigandEstAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}