
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ColExpeMarTableAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10381, -2, 1, 0}// 11	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ColExpeMarTableAddonDeed();
			}
		}

		[ Constructable ]
		public ColExpeMarTableAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5559, -1, 1, 2, 2142, -1, "Banniere avec logo de la Compagnie d'expedition marchande de casterral", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2910, -1, 0, 0, 2142, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2603, 0, 1, 0, 2142, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2603, 2, 0, 1, 2142, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2603, 1, 1, 0, 2142, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2581, 0, 0, 5, 2142, 2, "Compagnie d'expedition marchande", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4495, 1, 0, 0, 2142, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4495, 0, 0, 0, 2142, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2910, 0, -1, 0, 2142, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2910, 1, -1, 0, 2142, -1, "", 1);// 10

		}

		public ColExpeMarTableAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ColExpeMarTableAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ColExpeMarTableAddon();
			}
		}

		[Constructable]
		public ColExpeMarTableAddonDeed()
		{
			Name = "ColExpeMarTable";
		}

		public ColExpeMarTableAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}