
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class QuaiduPortAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2500, -1, 13, 28}, {2602, -1, 10, 22}, {2602, 0, 11, 23}// 2	3	4	
			, {2602, 0, 12, 23}, {2602, 0, 13, 22}, {2602, -2, 11, 22}// 5	6	7	
			, {2602, -2, 12, 22}, {2602, -2, 13, 22}, {4576, -1, 11, 22}// 8	9	10	
			, {4577, -1, 12, 22}, {4575, -1, 13, 22}, {4014, 4, 12, 23}// 11	12	13	
			, {4014, 3, 13, 22}, {2591, -4, 14, 30}, {2321, -1, 10, 22}// 14	15	16	
			, {2321, -3, 11, 22}, {525, 5, 11, 20}, {933, 4, 13, 20}// 17	18	19	
			, {933, 4, 13, 14}, {933, 4, 13, 14}, {933, 4, 13, 14}// 20	21	22	
			, {933, 4, 13, 14}, {933, 4, 13, 14}, {933, 4, 13, 14}// 23	24	25	
			, {933, 4, 13, 14}, {933, 4, 13, 14}, {933, 4, 13, 9}// 26	27	28	
			, {933, 4, 13, 4}, {933, 4, 8, 23}, {933, 4, 8, 19}// 29	30	31	
			, {933, 4, 8, 14}, {933, 4, 8, 9}, {933, 4, 8, 4}// 32	33	34	
			, {938, 4, 13, 22}, {936, 4, 14, 29}, {936, 3, 14, 29}// 36	37	38	
			, {936, 2, 14, 29}, {936, 1, 14, 29}, {936, 0, 14, 29}// 39	40	41	
			, {936, -1, 14, 29}, {936, -2, 14, 29}, {936, -3, 14, 29}// 42	43	44	
			, {937, 4, 12, 25}, {937, 4, 11, 25}, {937, 4, 10, 25}// 45	46	47	
			, {937, 4, 9, 25}, {937, 4, 8, 25}, {5363, -3, 3, 30}// 48	49	106	
			, {5361, -3, 3, 28}, {2879, -3, 3, 22}, {2602, -3, 4, 22}// 107	108	109	
			, {2602, -2, 3, 22}, {2602, -4, 3, 23}, {2321, 2, -1, 23}// 110	111	112	
			, {2321, 3, 4, 23}, {2321, -1, 5, 22}, {2321, 2, 7, 23}// 113	114	115	
			, {2321, -3, 4, 22}, {2321, 4, -3, 23}, {2321, 1, -3, 23}// 116	117	118	
			, {933, -1, -5, 20}, {933, 4, 2, 23}, {933, -1, -5, 23}// 119	120	121	
			, {933, 4, -5, 23}, {933, 4, 2, 20}, {933, 4, 2, 21}// 122	123	124	
			, {933, 4, 2, 15}, {933, 4, 2, 10}, {933, 4, 2, 5}// 125	126	127	
			, {933, 4, 2, 0}, {933, 4, -5, 20}, {933, 4, -5, 20}// 128	129	130	
			, {933, 4, -5, 15}, {933, 4, -5, 10}, {933, 4, -5, 5}// 131	132	133	
			, {938, -1, 2, 24}, {936, -2, 2, 25}, {936, -3, 2, 25}// 134	135	136	
			, {936, -4, 2, 25}, {936, -5, 2, 25}, {937, -1, 1, 25}// 137	138	139	
			, {937, -1, 0, 25}, {937, -1, -1, 25}, {937, -1, -2, 25}// 140	141	142	
			, {937, -1, -3, 25}, {937, -1, -4, 25}, {937, -1, -5, 25}// 143	144	145	
			, {937, -1, -6, 25}, {937, -1, -7, 25}, {937, -1, -8, 25}// 146	147	148	
			, {937, 4, 7, 25}, {937, 4, 6, 25}, {937, 4, 5, 25}// 149	150	151	
			, {937, 4, 4, 25}, {937, 4, 3, 25}, {937, 4, 2, 25}// 152	153	154	
			, {937, 4, 1, 25}, {937, 4, 0, 25}, {937, 4, -1, 25}// 155	156	157	
			, {937, 4, -2, 25}, {937, 4, -3, 25}, {937, 4, -4, 25}// 158	159	160	
			, {937, 4, -5, 25}, {937, 4, -6, 25}, {937, 4, -7, 25}// 161	162	163	
			, {937, 4, -8, 25}, {1996, -1, 2, 22}, {1996, -2, 2, 22}// 164	170	176	
			, {2321, 2, -10, 23}, {933, -1, -11, 20}, {933, -1, -11, 23}// 265	266	267	
			, {933, 4, -11, 23}, {933, 4, -11, 21}, {933, 4, -11, 21}// 268	269	270	
			, {933, 4, -11, 16}, {933, 4, -11, 11}, {933, 3, -12, 2}// 271	272	273	
			, {933, 4, -11, 6}, {933, 4, -11, 1}, {937, -1, -9, 25}// 274	275	276	
			, {937, -1, -10, 25}, {937, -1, -11, 25}, {937, -1, -12, 25}// 277	278	279	
			, {937, -1, -13, 25}, {937, 4, -9, 25}, {937, 4, -10, 25}// 280	281	282	
			, {937, 4, -11, 25}, {937, 4, -12, 25}// 283	284	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new QuaiduPortAddonDeed();
			}
		}

		[ Constructable ]
		public QuaiduPortAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2586, -3, 14, 44, 0, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1997, 4, 12, 22, 864, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1996, -1, 12, 22, 761, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1996, -1, 11, 22, 761, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1996, -1, 10, 22, 761, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1996, -1, 9, 22, 761, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1996, -1, 8, 22, 761, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1996, -2, 12, 22, 761, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1996, -2, 11, 22, 761, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1996, -2, 10, 22, 761, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1996, -2, 9, 22, 761, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1996, -2, 8, 22, 761, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1996, -3, 12, 22, 761, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1996, -3, 11, 22, 761, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1996, -3, 10, 22, 761, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1996, -3, 9, 22, 761, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1996, -3, 8, 22, 761, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1997, 4, 13, 22, 864, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1997, 4, 11, 22, 864, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1997, 3, 12, 22, 761, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1997, 3, 11, 22, 761, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1997, 2, 12, 22, 760, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1997, 2, 11, 22, 761, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1997, 1, 12, 22, 761, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1997, 1, 11, 22, 760, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1997, 0, 12, 22, 864, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1997, 0, 11, 22, 761, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1997, 4, 11, 22, 864, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1997, 3, 11, 22, 761, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1997, 2, 11, 22, 760, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1997, 1, 11, 22, 761, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1997, 0, 11, 22, 761, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1993, 4, 13, 22, 864, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1993, 3, 13, 22, 864, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1993, 2, 13, 22, 864, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1997, 4, 10, 22, 864, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1997, 4, 9, 22, 864, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1997, 4, 8, 22, 864, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1997, 3, 11, 22, 761, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1997, 3, 10, 22, 761, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1997, 3, 9, 22, 761, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1997, 3, 8, 22, 761, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1997, 2, 10, 22, 760, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1997, 2, 9, 22, 760, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1997, 2, 8, 22, 760, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1997, 1, 10, 22, 761, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1997, 1, 9, 22, 761, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1997, 1, 8, 22, 761, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1997, 0, 11, 22, 864, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1997, 0, 10, 22, 864, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1997, 0, 9, 22, 864, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1997, 0, 8, 22, 864, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1993, 2, 13, 22, 864, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1993, 1, 13, 22, 864, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1993, 0, 13, 22, 864, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1993, -1, 13, 22, 864, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1993, -2, 13, 22, 864, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1993, -3, 13, 22, 864, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1996, -1, 7, 22, 761, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1996, -1, 6, 22, 761, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1996, -1, 5, 22, 761, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1996, -1, 4, 22, 761, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1996, -1, 3, 22, 761, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1996, -2, 7, 22, 761, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1996, -2, 6, 22, 761, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1996, -2, 5, 22, 761, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1996, -2, 4, 22, 761, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1996, -2, 3, 22, 761, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1996, -3, 7, 22, 761, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1996, -3, 6, 22, 761, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1996, -3, 5, 22, 761, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1996, -3, 4, 22, 761, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1996, -3, 3, 22, 761, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1993, -1, 2, 22, 864, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1993, -2, 2, 22, 864, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1993, -3, 2, 22, 864, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1997, 0, 7, 22, 864, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1997, 1, 7, 22, 761, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1997, 2, 7, 22, 760, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1997, 3, 7, 22, 761, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1997, 4, 7, 22, 864, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1997, 4, 6, 22, 864, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1997, 4, 5, 22, 864, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1997, 4, 4, 22, 864, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1997, 4, 3, 22, 864, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1997, 4, 2, 22, 864, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1997, 4, 1, 22, 864, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1997, 4, 0, 22, 864, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1997, 4, -1, 22, 864, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1997, 4, -2, 22, 864, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1997, 4, -3, 22, 864, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1997, 4, -4, 22, 864, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1997, 4, -5, 22, 864, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1997, 4, -6, 22, 864, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1997, 4, -7, 22, 864, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1997, 4, -8, 22, 864, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1997, 3, 6, 22, 761, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1997, 3, 5, 22, 761, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1997, 3, 4, 22, 761, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1997, 3, 3, 22, 761, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1997, 3, 2, 22, 761, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1997, 3, 1, 22, 761, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1997, 3, 0, 22, 761, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1997, 3, -1, 22, 761, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1997, 3, -2, 22, 761, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1997, 3, -3, 22, 761, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1997, 3, -4, 22, 761, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1997, 3, -5, 22, 761, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1997, 3, -6, 22, 761, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1997, 3, -7, 22, 761, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1997, 3, -8, 22, 761, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1997, 2, 6, 22, 760, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 1997, 2, 5, 22, 760, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1997, 2, 4, 22, 760, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1997, 2, 3, 22, 760, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1997, 2, 2, 22, 760, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1997, 2, 1, 22, 760, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1997, 2, 0, 22, 760, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1997, 2, -1, 22, 760, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1997, 2, -2, 22, 760, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1997, 2, -3, 22, 760, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1997, 2, -4, 22, 760, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1997, 2, -5, 22, 760, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1997, 2, -6, 22, 760, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1997, 2, -7, 22, 760, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1997, 2, -8, 22, 760, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1997, 1, 6, 22, 761, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1997, 1, 5, 22, 761, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1997, 1, 4, 22, 761, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1997, 1, 3, 22, 761, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 1997, 1, 2, 22, 761, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1997, 1, 1, 22, 761, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1997, 1, 0, 22, 761, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1997, 1, -1, 22, 761, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1997, 1, -2, 22, 761, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1997, 1, -3, 22, 761, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1997, 1, -4, 22, 761, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1997, 1, -5, 22, 761, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1997, 1, -6, 22, 761, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1997, 1, -7, 22, 761, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1997, 1, -8, 22, 761, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1997, 0, 6, 22, 864, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1997, 0, 5, 22, 864, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1997, 0, 4, 22, 864, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1997, 0, 3, 22, 864, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1997, 0, 2, 22, 864, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1997, 0, 1, 22, 864, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1997, 0, 0, 22, 864, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 1997, 0, -1, 22, 864, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1997, 0, -2, 22, 864, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1997, 0, -3, 22, 864, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1997, 0, -4, 22, 864, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1997, 0, -5, 22, 864, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 1997, 0, -6, 22, 864, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1997, 0, -7, 22, 864, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1997, 0, -8, 22, 864, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1849, 4, -13, 23, 864, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 1849, 3, -13, 23, 864, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1849, 2, -13, 23, 864, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 1849, 1, -13, 23, 864, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 1849, 0, -13, 23, 864, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 1997, 4, -11, 22, 864, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 1997, 4, -12, 22, 864, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1997, 4, -13, 22, 864, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1997, 3, -11, 22, 761, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1997, 3, -12, 22, 761, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1997, 3, -13, 22, 864, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1997, 2, -11, 22, 760, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1997, 2, -12, 22, 760, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1997, 2, -13, 22, 864, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1997, 1, -11, 22, 761, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 1997, 1, -12, 22, 761, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1997, 1, -13, 22, 864, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1997, 0, -11, 22, 864, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1997, 0, -12, 22, 864, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1997, 0, -13, 22, 864, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1997, 0, -9, 22, 864, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1997, 1, -9, 22, 761, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1997, 2, -9, 22, 760, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1997, 3, -9, 22, 761, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1997, 4, -9, 22, 864, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1997, 4, -10, 22, 864, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1997, 3, -10, 22, 761, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1997, 2, -10, 22, 760, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1997, 1, -10, 22, 761, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1997, 0, -10, 22, 864, -1, "", 1);// 314

		}

		public QuaiduPortAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class QuaiduPortAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new QuaiduPortAddon();
			}
		}

		[Constructable]
		public QuaiduPortAddonDeed()
		{
			Name = "QuaiduPort";
		}

		public QuaiduPortAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}