namespace Server.Custom.Aptitudes
{
	public enum Aptitude
	{
		Chimie = 0,
		Couture = 1,
		Ebenisterie = 2,
		Economie = 3,
		FabricationArc = 4,
		Ingenierie = 5,
		Metallurgie = 6,
		Musique = 7,
		Transcription = 8,
		BouclierGardien = 9,
		CombatAuSol = 10,
		CombatEquestre = 11,
		CoupPrecis = 12,
		Endurance = 13,
		Esquive = 14,
		LancerPrecis = 15,
		Sacrifice = 16,
		TueurDeMonstres = 17,
		BonusDivin = 18,
		Concentration = 19,
		ConnaissancesAccrues = 20,
		DevouementCeleste = 21,
		FerveurReligieuse = 22,
		MagieProlongee = 23,
		PouvoirDivin = 24,
		Receptacle = 25,
		RegenerationPdP = 26,
		SortsOffensifs = 27,
		SortsDefensifs = 28,
		Botanique = 29,
		Equitation = 30,
		Familier = 31,
		LibreDeplacementDesert = 32,
		LibreDeplacementForet = 33,
		LibreDeplacementJungle = 34,
		LibreDeplacementMarais = 35,
		LibreDeplacementNeige = 36,
		PassageSylvestre = 37,
		Assassinat = 38,
		Deguisement = 39,
		PosePieges = 40,
		ManiementDuFouet = 41,
		Cognition = 42,
		Ecriture = 43,
		Etude = 44,
		LancerCouteaux = 45
	}
}
